### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by Haidy777** [Haidy777/bit-trader#1]
This is the main tracking Issue for the road to version 1.0

# TODOs
## generic tasks
 - [ ] docu
 - [ ] (#2) extract kraken api implementation to own abstract class (so more exchanges can be implemented)
 - [ ] change subprocess (watcher, trader, reporter) to standalones (so they can communicate through socketes/ports -> might be useful for docker instances) (would make it easier to debug)
 - [ ] (#3) backtesting
 - [x] create issues for this issues
 - [ ] (#4) error handling
 - [ ] (#6) logging should be done through one central station (levels should be set and changeable)
 - [ ] (#7) tests, tests and tests
 - [ ] (#15) extract child-process creation and destruction functionality to separate class
 - [ ] (#17) convert codebase to typescript
 - [x] (#18) editorconfig

## strategies
 - [ ] (#5) restart persitancy

### "mirco-trades"
- [ ] (#8) make start & stoppable
- [ ] (#9) better reporting of orders (standard implementation for strategies?)
- [ ] (#10) report time of requests / tading decisions
- [ ] (#20) max. open time for buy order
- [ ] (#21) order duplication / random exits

### "fixed-step-down"
- [ ] (#11)
strategy example:
```
buy 10 at 2
buy 10 at 1.95
buy 10 at 1.90
buy 10 at 1.85
sell 40 at 2.05
```
buy x (10) units at y price drop, sell over the break even limit (in the example 1.925)

### "fibonacci double flip"
 - [ ] (#19)

## reporter
 - [ ] (#12) reporter for trades
 - [ ] (#13) mysql-reporter

## controllers
 - [ ] (#14) control bot through telegram
